

import { AppStep, AppState, EmailTemplate, UserSignature } from './types';

export const DEFAULT_SIGNATURE: UserSignature = {
  id: 'default-sig',
  name: 'Professionnel',
  content: '<b>Votre Nom</b><br/><i>Poste</i><br/>Nom de l\'Entreprise',
  isDefault: true,
  data: {
    name: 'Votre Nom',
    title: 'Poste',
    company: 'Nom de l\'Entreprise',
    logo: ''
  }
};

export const DEFAULT_CATEGORIES: string[] = [
  'Officiel & Protocolaire',
  'Événementiel',
  'Rotary & Associatif',
  'Networking & Affaires',
  'Quotidien & Bureau',
  'SMS & Messagerie',
  'Réseaux Sociaux'
];

export const INITIAL_STATE: AppState = {
  step: AppStep.SCAN,
  currentContact: null,
  history: [],
  signatures: [DEFAULT_SIGNATURE],
  categories: DEFAULT_CATEGORIES,
  templates: [], // Will be populated in App.tsx
  isDarkMode: false,
  processingStatus: '',
};

// Helper to generate IDs
const t = (category: any, names: string[]): EmailTemplate[] => {
  return names.map((name, idx) => ({
    id: `${category.substring(0,3)}-${idx}`,
    category,
    name
  }));
};

export const EMAIL_TEMPLATES: EmailTemplate[] = [
  ...t('Officiel & Protocolaire', [
    "Salutations à un nouvel Ambassadeur",
    "Salutations à un nouveau Préfet",
    "Félicitations pour une élection (Maire/Député)",
    "Félicitations pour une réélection",
    "Félicitations pour une nomination ministérielle",
    "Félicitations pour une distinction (Légion d'honneur)",
    "Demande d'audience au Maire",
    "Demande d'audience au Préfet",
    "Demande d'audience à un Député/Sénateur",
    "Suivi de demande d'audience (relance respectueuse)",
    "Remerciement après une audience officielle",
    "Invitation à inaugurer un bâtiment (Ruban)",
    "Invitation à présider une cérémonie",
    "Demande de Haut Patronage",
    "Demande de subvention publique",
    "Envoi de rapport d'activité aux élus",
    "Signalement d'un problème de voirie/sécurité (officiel)",
    "Courrier de soutien à une action municipale",
    "Lettre ouverte (contexte de crise)",
    "Réponse à une sollicitation d'élu",
    "Excuse pour absence à une cérémonie officielle",
    "Désignation d'un représentant pour une cérémonie",
    "Message de condoléances (décès personnalité locale)",
    "Message de condoléances (catastrophe nationale)",
    "Vœux de Nouvel An institutionnels",
    "Vœux de Fête Nationale",
    "Invitation au Consul (fête nationale étrangère)",
    "Demande de visa/passeport (procédure accélérée/appui)",
    "Remerciement aux forces de l'ordre/secours",
    "Invitation à un petit-déjeuner élus/entreprises",
    "Proposition de partenariat public-privé",
    "Demande de jumelage (ville ou entité)",
    "Accueil d'une délégation étrangère",
    "Note de cadrage protocolaire (pour visite)",
    "Annonce de prise de fonction officielle",
    "Annonce de départ en retraite (cadre officiel)",
    "Démission d'un mandat électif ou associatif",
    "Hommage à un prédécesseur",
    "Transmission de dossier confidentiel",
    "Invitation à une commémoration",
    "Discours de bienvenue officiel (trame écrite)",
    "Remerciement pour l'octroi d'une salle municipale",
    "Contestation administrative formelle (recours gracieux)",
    "Demande de permis/autorisation exceptionnelle",
    "Lettre de recommandation institutionnelle",
    "Notification de changement de statut juridique",
    "Invitation déjeuner protocolaire",
    "Plan de table (envoi aux invités d'honneur)",
    "Cadeau diplomatique (mot d'accompagnement)",
    "Clôture de mandat (message de départ)"
  ]),
  ...t('Événementiel', [
    "Teaser (J-60)",
    "Save the Date (J-45)",
    "Invitation VIP (Personnalisée)",
    "Invitation Speaker / Intervenant",
    "Invitation Presse / Média",
    "Invitation Partenaires / Sponsors",
    "Invitation Grand Public (Newsletter)",
    "Invitation avec tarif 'Early Bird'",
    "Relance invitation (J-15)",
    "Relance 'Derniers jours pour s'inscrire'",
    "Confirmation d'inscription",
    "Envoi du billet / QR Code",
    "Partage du programme détaillé",
    "Annonce d'un 'Guest Star'",
    "Infos pratiques (Plan d'accès, Parking, Hôtels)",
    "Demande de régime alimentaire spécial",
    "Briefing technique pour les intervenants",
    "Demande de présentation (PowerPoint) aux speakers",
    "Rappel J-1 ('À demain !')",
    "Message 'En direct' (pendant l'événement)",
    "Message de bienvenue (sur écran ou app)",
    "Annonce de changement de salle/horaire (urgence)",
    "Remerciement aux participants (J+1)",
    "Remerciement aux VIPs (personnalisé)",
    "Remerciement aux Sponsors (avec bilan visibilité)",
    "Remerciement aux Bénévoles/Staff",
    "Remerciement aux Intervenants",
    "Envoi des photos / Replay vidéo",
    "Envoi des présentations (slides)",
    "Demande de feedback (Enquête satisfaction)",
    "Partage de l'article de presse post-event",
    "Appel à idées pour la prochaine édition",
    "Ouverture des inscriptions 'Année suivante'",
    "Annonce 'Sold Out' (Complet)",
    "Gestion liste d'attente",
    "Refus d'entrée (poli, pour non-inscrit)",
    "Annonce d'annulation (force majeure)",
    "Annonce de report de date",
    "Proposition de remboursement",
    "Recherche de lieu (demande de devis salle)",
    "Recherche de traiteur (demande de devis)",
    "Validation de devis prestataire",
    "Briefing photographe/vidéaste",
    "Invitation cocktail post-conférence",
    "Invitation dîner de gala",
    "Save the Date (format papier/courrier)",
    "Relance téléphonique (script)",
    "Message pour objet trouvé (après event)",
    "Bilan financier (aux organisateurs)",
    "Clôture du dossier événement"
  ]),
  ...t('Rotary & Associatif', [
    "Bienvenue visiteur (post-réunion)",
    "Intronisation nouveau membre (Invitation cérémonie)",
    "Discours d'intronisation (trame)",
    "Parrainage : Proposition de filleul",
    "Parrainage : Lettre au filleul potentiel",
    "Nomination Comité (Président de commission)",
    "Convocation Assemblée Générale",
    "Envoi du PV d'Assemblée Générale",
    "Appel à cotisation annuel",
    "Relance cotisation (amicale)",
    "Relance cotisation (formelle)",
    "Invitation Conférencier externe",
    "Remerciement Conférencier (+ don au nom du speaker)",
    "Bulletin hebdomadaire (Le 'Compte-rendu')",
    "Annonce 'Action Professionnelle' (visite entreprise)",
    "Action Jeunesse (RYLA, Student Exchange) - Recherche",
    "Accueil étudiant d'échange (Message famille d'accueil)",
    "Organisation collecte (Banque Alimentaire)",
    "Planning des tours de garde (bénévolat)",
    "Vente de billets (Tombola/Loto)",
    "Demande de lot pour tombola (aux commerçants)",
    "Commande repas (au restaurateur du siège)",
    "Annulation réunion statutaire (vacances/férié)",
    "Délocalisation de réunion (sortie)",
    "Visite Gouverneur (Préparation)",
    "Remerciement visite Gouverneur",
    "Invitation Club Contact (Club jumelé étranger)",
    "Organisation déplacement (voyage du club)",
    "Vœux du Président",
    "Passation de pouvoir : Discours sortant",
    "Passation de pouvoir : Discours entrant",
    "Passation de pouvoir : Invitation",
    "Nomination Paul Harris Fellow (PHF)",
    "Décès d'un membre (Annonce au club)",
    "Décès d'un membre (Condoléances famille)",
    "Soutien membre malade (Hospitalisation)",
    "Démission d'un membre (Regrets)",
    "Demande de congé (Dispense d'assiduité)",
    "Partage info District (Conférence de district)",
    "Partage info Rotary International (Convention)",
    "Don Fondation Rotary (Appel aux dons)",
    "PolioPlus (Journée mondiale)",
    "Action inter-clubs (Proposition)",
    "Réunion de comité (Ordre du jour)",
    "Gestion des effectifs (Bilan recrutement)",
    "Communication presse locale (Article sur une action)",
    "Invitation Maire à une action",
    "Demande d'autorisation vente sur voie publique",
    "Certificat de reconnaissance bénévole",
    "Minute rotarienne (Thème de réflexion)"
  ]),
  ...t('Networking & Affaires', [
    "Message post-rencontre (standard)",
    "Message post-rencontre ('J'ai adoré notre échange sur X')",
    "Invitation déjeuner d'affaires",
    "Invitation café 'brise-glace'",
    "Invitation afterwork",
    "Demande de conseil ('J'ai besoin de votre expertise')",
    "Demande d'introduction (via tiers)",
    "Mise en relation (A et B, je vous présente...)",
    "Suivi de mise en relation ('Est-ce que ça a matché ?')",
    "Félicitations nouveau poste",
    "Félicitations article presse / passage média",
    "Félicitations levée de fonds",
    "Félicitations anniversaire d'entreprise",
    "Envoi d'article pertinent ('J'ai pensé à vous')",
    "Envoi de livre blanc / étude",
    "Proposition de collaboration / Synergie",
    "Demande de partenariat commercial",
    "Demande de recommandation / Témoignage",
    "Remerciement pour recommandation",
    "Reprendre contact (3 mois sans nouvelles)",
    "Reprendre contact (1 an sans nouvelles)",
    "Vœux de nouvelle année (Networking)",
    "Message pré-vacances ('On se voit à la rentrée ?')",
    "Message de rentrée ('Prêt pour l'automne ?')",
    "Annonce changement de poste (à son réseau)",
    "Invitation lancement produit",
    "Invitation portes ouvertes",
    "Proposition de tribune commune / Co-écriture",
    "Demande de mentorat (être mentoré)",
    "Proposition de mentorat (devenir mentor)",
    "Invitation à rejoindre un cercle/club d'affaires",
    "Refus de sollicitation commerciale (poli)",
    "Refus de RDV (manque de temps)",
    "Report de RDV (imprévu)",
    "Annulation de RDV (urgence)",
    "Relance douce ('Avez-vous eu le temps de lire ?')",
    "Relance humour ('Mon mail a dû tomber dans les spams')",
    "Closing (Dernière relance avant abandon)",
    "Demande d'avis sur un projet",
    "Invitation à un webinaire",
    "Partage de son propre contenu (newsletter)",
    "Demande de contact clé (DRH, Directeur Achat...)",
    "Message de sympathie (après échec/coup dur connu)",
    "Invitation déjeuner 'sans agenda'",
    "Proposition de covoiturage pour un événement",
    "Réaction à une Story (Social Media)",
    "Commentaire public valorisant",
    "Recommandation de prestataire (Donner un bon plan)",
    "Cadeau d'affaires (Mot d'accompagnement)",
    "Networking inversé (Demander : 'Comment puis-je t'aider ?')"
  ]),
  ...t('Quotidien & Bureau', [
    "Accusé de réception (Simple)",
    "Accusé de réception (Avec délai estimé)",
    "Message d'absence (Congés)",
    "Message d'absence (Déplacement/Formation)",
    "Message d'absence (Maladie/Imprévu)",
    "Message d'absence (Pont/Férié)",
    "Retour de congés ('Je traite les mails en retard')",
    "Demande de congés",
    "Demande de RTT",
    "Demande de télétravail",
    "Prévenir d'un retard le matin",
    "Prévenir d'un départ anticipé le soir",
    "Arrêt maladie (Envoi justificatif)",
    "Bienvenue nouveau collègue (Onboarding)",
    "Message de départ (Pot de départ)",
    "Message de démission (formel)",
    "Convocation réunion d'équipe",
    "Envoi Ordre du jour réunion",
    "Envoi Compte-rendu réunion",
    "Demande de disponibilité (Doodle/Calendly)",
    "Confirmation horaire réunion",
    "Réservation de salle de réunion",
    "Demande de matériel / Fournitures",
    "Signalement panne informatique",
    "Envoi de dossier à valider",
    "Relance validation (Urgent)",
    "Transmission de facture",
    "Note de frais (Envoi)",
    "Demande d'acompte",
    "Envoi de devis (Client)",
    "Relance devis",
    "Envoi de facture (Client)",
    "Relance impayé (Niveau 1 : Oubli ?)",
    "Relance impayé (Niveau 2 : Rappel)",
    "Relance impayé (Niveau 3 : Mise en demeure)",
    "Réponse à candidature (Refus)",
    "Réponse à candidature (Demande entretien)",
    "Accueil stagiaire",
    "Félicitations équipe (Succès projet)",
    "Recadrage doux (Erreur commise)",
    "Organisation déjeuner d'équipe",
    "Collecte cadeau commun (Anniversaire/Départ)",
    "Objet trouvé dans les locaux",
    "Rappel consignes sécurité/propreté",
    "Demande d'accès (Badge, Code)",
    "Mise à jour coordonnées bancaires",
    "Partage revue de presse interne",
    "Bon week-end (Vendredi après-midi)",
    "Bonnes vacances (Été/Noël)",
    "Joyeux anniversaire (Collègue)"
  ]),
  ...t('SMS & Messagerie', [
    "'J'arrive dans 5 min'",
    "'Je suis là' (Sur place)",
    "'Je suis en bas' (Réception)",
    "'Désolé, gros bouchons, +10 min'",
    "'Bien reçu, merci !'",
    "'Ok pour moi' (Validation rapide)",
    "'Je regarde ça et je te dis' (Temporisation)",
    "'Tu as 2 min pour un appel ?'",
    "'Je suis en réunion, je te rappelle'",
    "'Peux pas répondre, envoie un sms'",
    "Partage de localisation",
    "Partage de contact",
    "'As-tu bien reçu mon mail ?' (Ping)",
    "'Pense à m'envoyer le fichier X' (Rappel flash)",
    "'Bon courage pour ta présentation !'",
    "'Bravo, c'était top !' (Feedback immédiat)",
    "'On déjeune ensemble ce midi ?'",
    "'Café ?' (Interne bureau)",
    "Photo de l'événement (Partage live)",
    "'C'est quoi le code de la porte ?'",
    "'Quel étage ?'",
    "'Tu es où dans la salle ?'",
    "'Je t'ai laissé un dossier sur ton bureau'",
    "'Merci pour hier soir'",
    "'Bonne route / Rentre bien'",
    "'Bon week-end !'",
    "Vœux Nouvel An (SMS liste diffusion)",
    "Joyeux Anniversaire (Court)",
    "'On confirme pour demain ?'",
    "'Je dois décaler de 15 min, c'est jouable ?'",
    "'Annulation de dernière minute, désolé' (Urgence)",
    "'Besoin d'aide ?'",
    "'Merci du coup de main'",
    "'J'ai oublié mon chargeur/badge...'",
    "Blague / Meme (Contexte détendu)",
    "'T'as vu cette news ?' (Lien article)",
    "Groupes : 'Bienvenue à X dans le groupe'",
    "Groupes : 'Info pour tous'",
    "Sondage rapide (Fonction vote)",
    "Réaction Emoji",
    "Message vocal : Explication complexe",
    "Message vocal : Récit anecdote",
    "Message vocal : Consigne rapide",
    "'Dispo ce soir ?' (Informel)",
    "'Rappelle-moi quand tu peux'",
    "'Urgent !'",
    "'C'est noté'",
    "'Pas de souci'",
    "'À toute !'",
    "'Bisous' (Proches uniquement !)"
  ]),
  ...t('Réseaux Sociaux', [
    "Invitation LinkedIn (Sans note)",
    "Invitation LinkedIn (Note : 'J'ai vu votre profil...')",
    "Invitation LinkedIn (Note : 'Suite à notre rencontre...')",
    "Invitation LinkedIn (Note : 'Contacts communs...')",
    "Invitation LinkedIn (Note : 'Lecteur de vos posts...')",
    "Message de bienvenue (Nouveau contact)",
    "'Merci d'avoir accepté mon invitation'",
    "Réaction 'J'aime'",
    "Réaction 'Bravo'",
    "Réaction 'Soutien'",
    "Réaction 'Instructif'",
    "Réaction 'Drôle'",
    "Commentaire : Félicitations simple",
    "Commentaire : Question ouverte pour engager",
    "Commentaire : Apport de valeur/nuance",
    "Commentaire : Tag d'un ami",
    "Repost (Partage simple)",
    "Repost avec avis (Quote)",
    "Création de post : Annonce nouveauté",
    "Création de post : Partage d'expertise",
    "Création de post : Coup de gueule (modéré)",
    "Création de post : Sondage",
    "Création de post : Célébration équipe",
    "Création de post : Retour d'événement (photos)",
    "Message Privé (DM) : Prospection directe",
    "DM : Prospection 'Soft'",
    "DM : Demande de partenariat",
    "DM : 'Off the record'",
    "DM : Remerciement pour un commentaire",
    "DM : Proposer un café virtuel",
    "Recommendation de compétence",
    "Rédaction d'une recommandation écrite (Profil)",
    "Demande de recommandation écrite",
    "Souhaiter un anniversaire (Notif LinkedIn)",
    "Féliciter pour un nouveau poste",
    "Féliciter pour X années dans l'entreprise",
    "Réponse à une Story",
    "Mention dans une Story",
    "Identification sur une photo",
    "Utilisation de hashtags pertinents",
    "Inscription à une Newsletter LinkedIn",
    "Participation à un événement LinkedIn",
    "Message au créateur d'un événement",
    "'Suivre' (Follow) sans connecter",
    "Activer la cloche (Notifications)",
    "Visite de profil (Laisser une trace)",
    "Bloquer/Signaler",
    "Mise à jour de son titre/résumé",
    "Message 'Open to Work'"
  ])
];
